### ISSUE TITLE
Issue in sql.NewExtendedServerBlobAuditingPolicy Arguments

### ISSUE THREAD

**Issue by prashantb1311** [pulumi/pulumi-azure-native#1328]
@mikhailshilkov : 
Now  I am facing issue in sql.NewExtendedServerBlobAuditingPolicy arguments as follows:

_"cannot use "Enabled" (constant of type string) as sql.BlobAuditingPolicyStateInput value in struct literal: missing method"_ 

My mod.go file has following content:

```
module demo1

go 1.14

require (
	github.com/pulumi/pulumi-azure-native/sdk v1.47.0
	github.com/pulumi/pulumi/sdk/v3 v3.18.1
)
```

And my main.go file is:
```
package main

import (
	sql "github.com/pulumi/pulumi-azure-native/sdk/go/azure/sql"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := sql.NewExtendedServerBlobAuditingPolicy(ctx, "extendedServerBlobAuditingPolicy", &sql.ExtendedServerBlobAuditingPolicyArgs{
			AuditActionsAndGroups: pulumi.StringArray{
				pulumi.String("SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP"),
				pulumi.String("FAILED_DATABASE_AUTHENTICATION_GROUP"),
				pulumi.String("BATCH_COMPLETED_GROUP"),
			},
			BlobAuditingPolicyName:       pulumi.String("default"),
			IsAzureMonitorTargetEnabled:  pulumi.Bool(true),
			IsStorageSecondaryKeyInUse:   pulumi.Bool(false),
			PredicateExpression:          pulumi.String("object_name = 'SensitiveData'"),
			QueueDelayMs:                 pulumi.Int(4000),
			ResourceGroupName:            pulumi.String("blobauditingtest-4799"),
			RetentionDays:                pulumi.Int(6),
			ServerName:                   pulumi.String("blobauditingtest-6440"),
			State:                        "Enabled",
			StorageAccountAccessKey:      pulumi.String("sdlfkjabc+sdlfkjsdlkfsjdfLDKFTERLKFDFKLjsdfksjdflsdkfD2342309432849328476458/3RSD=="),
			StorageAccountSubscriptionId: pulumi.String("00000000-1234-0000-5678-000000000000"),
			StorageEndpoint:              pulumi.String("https://mystorage.blob.core.windows.net"),
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

![image](https://user-images.githubusercontent.com/88548831/143858571-03e967ee-086d-4b09-ae34-1bc7634f9d0b.png)

_Originally posted by @prashantb1311 in https://github.com/pulumi/pulumi-azure-native/issues/1202#issuecomment-981539813_

**Comment by mikhailshilkov** [comment]
I think the error says it correctly: you need to pass `BlobAuditingPolicyStateInput` not a string.

**Comment by prashantb1311** [comment]
@mikhailshilkov  as per [documentation](https://www.pulumi.com/registry/packages/azure-native/api-docs/sql/extendedserverblobauditingpolicy/) state take string as input.
If this is updated in new version, could you please give us an example code?

**Comment by prashantb1311** [comment]
@mikhailshilkov  Pulumi destroy for NewExtendedServerBlobAuditingPolicy is not yet working as expected
mod.go file

```module demo1

go 1.14

require (
	github.com/pulumi/pulumi-azure-native/sdk v1.47.0
	github.com/pulumi/pulumi-random/sdk/v4 v4.3.1
	github.com/pulumi/pulumi/sdk/v3 v3.18.1
)
```

main.go 

```
package main

import (
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure/resources"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure/sql"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure/storage"
	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Create an Azure Resource Group
		resourceGroup, err := resources.NewResourceGroup(ctx, "sqlBlobAudit-rg", nil)
		if err != nil {
			return err
		}

		// Create an Azure resource (Storage Account)
		storageAccount, err := storage.NewStorageAccount(ctx, "sqlblobauditacct", &storage.StorageAccountArgs{
			ResourceGroupName: resourceGroup.Name,
			Sku: &storage.SkuArgs{
				Name: storage.SkuName_Standard_LRS,
			},
			Kind: storage.KindStorageV2,
		})
		if err != nil {
			return err
		}

		// Export the primary key of the Storage Account
		primaryStorageKey := pulumi.All(resourceGroup.Name, storageAccount.Name).ApplyT(
			func(args []interface{}) (string, error) {
				resourceGroupName := args[0].(string)
				accountName := args[1].(string)
				accountKeys, err := storage.ListStorageAccountKeys(ctx, &storage.ListStorageAccountKeysArgs{
					ResourceGroupName: resourceGroupName,
					AccountName:       accountName,
				})
				if err != nil {
					return "", err
				}

				return accountKeys.Keys[0].Value, nil
			}).(pulumi.StringOutput)

		if err != nil {
			return err
		}

		// create sql admin user
		username := "pulumiadmin"

		sqlpassword, err := random.NewRandomPassword(ctx, "loginpassword", &random.RandomPasswordArgs{
			Length:     pulumi.Int(14),
			MinLower:   pulumi.Int(4),
			MinUpper:   pulumi.Int(4),
			MinNumeric: pulumi.Int(4),
			Number:     pulumi.Bool(true),
			Special:    pulumi.Bool(false),
		})
		if err != nil {
			return err
		}

		// create an Azure sql server

		sqlServer, err := sql.NewServer(ctx, "sqlBlobAudit-sqlserver", &sql.ServerArgs{
			AdministratorLogin:         pulumi.String(username),
			AdministratorLoginPassword: sqlpassword.Result,
			ResourceGroupName:          resourceGroup.Name,
			Version:                    pulumi.String("12.0"),
		})
		if err != nil {
			return err
		}
		_, err = sql.NewExtendedServerBlobAuditingPolicy(ctx, "extendedServerBlobAuditingPolicy", &sql.ExtendedServerBlobAuditingPolicyArgs{
			AuditActionsAndGroups: pulumi.StringArray{
				pulumi.String("SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP"),
				pulumi.String("FAILED_DATABASE_AUTHENTICATION_GROUP"),
				pulumi.String("BATCH_COMPLETED_GROUP")},
			BlobAuditingPolicyName:       pulumi.String("default"),
			IsAzureMonitorTargetEnabled:  pulumi.Bool(true),
			IsDevopsAuditEnabled:         nil,
			IsStorageSecondaryKeyInUse:   pulumi.Bool(false),
			PredicateExpression:          pulumi.String("object_name = 'SensitiveData'"),
			QueueDelayMs:                 pulumi.Int(4000),
			ResourceGroupName:            resourceGroup.Name,
			RetentionDays:                pulumi.Int(6),
			ServerName:                   sqlServer.Name,
			State:                        sql.BlobAuditingPolicyStateEnabled,
			StorageAccountAccessKey:      primaryStorageKey,
			StorageAccountSubscriptionId: nil,
			StorageEndpoint:              storageAccount.PrimaryEndpoints.Blob(),
		})
		if err != nil {
			return err
		}

		// Outputs
		ctx.Export("resourcegroup_name", resourceGroup.Name)
		ctx.Export("storageaccount_name", storageAccount.Name)
		ctx.Export("sqladmin_user", pulumi.String(username))
		ctx.Export("sqladmin_password", sqlpassword.Result)
		ctx.Export("primarystoragekey", pulumi.ToSecret(primaryStorageKey))
		ctx.Export("sqlserver_name", sqlServer.Name)

		return nil
	})

}


```

pulumi destroy output:
```
Previewing destroy (dcs0009940):
     Type                                                  Name                              Plan
 -   pulumi:pulumi:Stack                                   demo1-dcs0009940                  delete
 -   ├─ azure-native:sql:ExtendedServerBlobAuditingPolicy  extendedServerBlobAuditingPolicy  delete
 -   ├─ azure-native:storage:StorageAccount                sqlblobauditacct                  delete
 -   ├─ azure-native:sql:Server                            sqlBlobAudit-sqlserver            delete
 -   ├─ random:index:RandomPassword                        loginpassword                     delete
 -   └─ azure-native:resources:ResourceGroup               sqlBlobAudit-rg                   delete

Outputs:
  - primarystoragekey  : "[secret]"
  - resourcegroup_name : "sqlBlobAudit-rg2fc24da7"
  - sqladmin_password  : "[secret]"
  - sqladmin_user      : "pulumiadmin"
  - sqlserver_name     : "sqlblobaudit-sqlserverfd8e482d"
  - storageaccount_name: "sqlblobauditacct9ba1b8ef"

Resources:
    - 6 to delete

Do you want to perform this destroy? yes
Destroying (dcs0009940):
     Type                                                  Name                              Status                  Info
     pulumi:pulumi:Stack                                   demo1-dcs0009940                  **failed**              1 error
 -   └─ azure-native:sql:ExtendedServerBlobAuditingPolicy  extendedServerBlobAuditingPolicy  **deleting failed**     1 error

Diagnostics:
  azure-native:sql:ExtendedServerBlobAuditingPolicy (extendedServerBlobAuditingPolicy):
    error: Code="InvalidServerBlobAuditingPolicyCreateRequest" Message="The create server blob auditing policy request does not exist or has no properties object."

  pulumi:pulumi:Stack (demo1-dcs0009940):
    error: update failed

Resources:

Duration: 1s
```

**Comment by mikhailshilkov** [comment]
@prashantb1311 This last error was fixed in 1.48.0 see #1202

**Comment by prashantb1311** [comment]
@mikhailshilkov  I tried using 1.48.0 but still failing with same error:

go.mod
```
go 1.16

require (
	github.com/google/uuid v1.3.0
	github.com/pulumi/pulumi-azure-native/sdk v1.48.0
	github.com/pulumi/pulumi/sdk/v3 v3.18.1
)

```

output:
```
Diagnostics:
  azure-native:sql:ServerBlobAuditingPolicy (serverBlobAuditingPolicydev):
    error: Code="InvalidServerBlobAuditingPolicyCreateRequest" Message="The create server blob auditing policy request does not exist or has no properties object."

```

**Comment by prashantb1311** [comment]
@mikhailshilkov  Thank you so much. Now things are working fine for server.
I really appreciate your efforts and help.
