### ISSUE TITLE
Support for AMR High Availability Property

### ISSUE THREAD

**Issue by thechucklingatom** [pulumi/pulumi-azure-native#4241]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When deploying the new Azure Managed Redis instances with pulumi I cannot select to not deploy a High Availability instance. You can see the property listed on the api [here](https://github.com/Azure/azure-rest-api-specs/blob/737d276c61674f351c2d8ff06c69341ee0f7a598/specification/redisenterprise/resource-manager/Microsoft.Cache/preview/2025-05-01-preview/redisenterprise.json#L1981)

I attempted to add this version when using a pulumi package add and was unable to. A new issue was requested on #3919 if something was found to be missing

### Affected area/feature

redisenterprise.RedisEnterprise

**Comment by mjeffryes** [comment]
Yes, from our [docs](https://www.pulumi.com/registry/packages/azure-native/api-docs/redisenterprise/redisenterprise/), it looks like our default version for `redisenterprise` is `2024-03-01-preview` and you need version `2025-05-01-preview` to send the `highAvailability` field. 

However, you should be able to get a local SDK for the `2025-05-01-preview` API version using `pulumi package add` as described in the [Azure Native version guide](https://www.pulumi.com/registry/packages/azure-native/version-guide/#accessing-any-api-version-via-local-packages). You might need to update to the latest version of the azure-native provider for that to work though since the API version you want to use is fairly recent.

**Comment by thechucklingatom** [comment]
I have tried running the command with the latest version of the azure-native plugin and I am getting syntax errors generating off that schema.

**Comment by Zaid-Ajaj** [comment]
@thechucklingatom can you elaborate more on the errors you are encountering? that might be a bug in our code generators

**Comment by thechucklingatom** [comment]
This is the error I am experiencing
``` pulumi package add azure-native redisEnterprise 2025-05-01-preview
error: failed to get schema. Diagnostics: <nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:AccessPolicyAssignment/properties/user/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:AccessPolicyAssignment/inputProperties/user/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:Database/properties/geoReplication/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:Database/properties/systemData/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:Database/properties/modules/items/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:Database/properties/persistence/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:Database/inputProperties/persistence/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:Database/inputProperties/geoReplication/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:Database/inputProperties/modules/items/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:PrivateEndpointConnection/properties/privateEndpoint/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:PrivateEndpointConnection/properties/privateLinkServiceConnectionState/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:PrivateEndpointConnection/inputProperties/privateLinkServiceConnectionState/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:RedisEnterprise/properties/privateEndpointConnections/items/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:RedisEnterprise/properties/encryption/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:RedisEnterprise/properties/identity/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:RedisEnterprise/properties/sku/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:RedisEnterprise/inputProperties/encryption/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:RedisEnterprise/inputProperties/identity/$ref: unknown primitive type object;
<nil>: #/resources/azure-native_redisEnterprise_v20250501preview:redisEnterprise:RedisEnterprise/inputProperties/sku/$ref: unknown primitive type object;
<nil>: #/functions/azure-native_redisEnterprise_v20250501preview:redisEnterprise:listRedisEnterpriseSkusForScaling/outputs/properties/skus/items/$ref: unknown primitive type object;
<nil>: #/types/azure-native_redisEnterprise_v20250501preview:redisEnterprise:ClusterPropertiesCustomerManagedKeyEncryption/properties/keyEncryptionKeyIdentity/$ref: unknown primitive type object;
<nil>: #/types/azure-native_redisEnterprise_v20250501preview:redisEnterprise:ClusterPropertiesEncryption/properties/customerManagedKeyEncryption/$ref: unknown primitive type object;
<nil>: #/types/azure-native_redisEnterprise_v20250501preview:redisEnterprise:ClusterPropertiesResponseCustomerManagedKeyEncryption/properties/keyEncryptionKeyIdentity/$ref: unknown primitive type object;
<nil>: #/types/azure-native_redisEnterprise_v20250501preview:redisEnterprise:ClusterPropertiesResponseEncryption/properties/customerManagedKeyEncryption/$ref: unknown primitive type object;
<nil>: #/types/azure-native_redisEnterprise_v20250501preview:redisEnterprise:DatabasePropertiesGeoReplication/properties/linkedDatabases/items/$ref: unknown primitive type object;
<nil>: #/types/azure-native_redisEnterprise_v20250501preview:redisEnterprise:DatabasePropertiesResponseGeoReplication/properties/linkedDatabases/items/$ref: unknown primitive type object;
<nil>: #/types/azure-native_redisEnterprise_v20250501preview:redisEnterprise:ManagedServiceIdentityResponse/properties/userAssignedIdentities/additionalProperties/$ref: unknown primitive type object;
 pulumi plugin ls
NAME          KIND      VERSION  SIZE    INSTALLED    LAST USED
azure-native  resource  3.6.1    438 MB  3 hours ago  10 minutes ago
TOTAL plugin cache size: 438 MB```

**Comment by Zaid-Ajaj** [comment]
thanks a lot for sharing the error, this looks like a bug with generating a valid schema for the resources in question.

**Comment by BrianVallelunga** [comment]
Any update on getting this to work?

**Comment by flo-sch** [comment]
I believe it was fixed by #4279 and released in [v3.8.0](https://github.com/pulumi/pulumi-azure-native/releases/tag/v3.8.0).
The default azure api version is also updated to `2025-05-01-preview`.

**Comment by thechucklingatom** [comment]
> I believe it was fixed by #4279 and released in [v3.8.0](https://github.com/pulumi/pulumi-azure-native/releases/tag/v3.8.0).
> The default azure api version is also updated to `2025-05-01-preview`.

When I pulled that version for I still get the schema generate error for those versions.

**Comment by flo-sch** [comment]
I just tried using `@pulumi/azure-native` v3.8.0 (typescript) and managed to create a cluster with `highAvailability: "Disabled"`

I think the commit I mentioned fixed how some parameters are forwarded to the azure API, it was more than just update the azure API version and specs.

**Comment by thechucklingatom** [comment]
This does appear to be working for generating AMR resources. I still cannot generate preview versions of the API, but the base need of being able to create a resource is resolved.
