### ISSUE TITLE
Subscription not found when creating a resourceGroup

### ISSUE THREAD

**Issue by staunerc** [pulumi/pulumi-azure-native#4319]
### What happened?

I get this error when I try to create a ResourceGroup (while preview step): 
"Subscription '"UUID"' not found. Check the spelling and casing and try again."

This error occurs with version 3.8.0 of the @pulumi/azure-native package. It works with version 3.7.0.

### Example

`
new resources.ResourceGroup("rg-test", {
    resourceGroupName: "rg-test",
  }),
`

### Output of `pulumi about`

CLI
Version      3.171.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  3.171.0

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.26100 Build 26100
Arch     x86_64

Nodejs: v22.14.0

Found no resources associated with prd

Found no pending operations associated with prd

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stooj** [comment]
I believe this is happening because of the way pulumi constructs a string of arguments to pass to the `az` command: https://github.com/pulumi/pulumi-azure-native/blob/ab2c3c1e9611261e9fe2d643e2c19fd33aa18256/provider/pkg/provider/azure_cli.go#L58

Should it pass an array of args instead?

Here's a sample Go program to demonstrate the difference:

```go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os/exec"
)

func main() {
	commandLine := `az account show -o json `

	flag.Parse()
	subscriptionId := flag.Arg(0)

	if subscriptionId != "" {
		commandLine += ` --subscription "` + subscriptionId + `"`
	}

	var cliCmd *exec.Cmd

	// Windows version
	// cliCmd = exec.Command("cmd.exe", "/C", commandLine)
	// Linux version
	cliCmd = exec.Command("/bin/sh", "-c", commandLine)
	fmt.Printf("Args: %#v\n", cliCmd.Args)

	var stdout, stderr bytes.Buffer
	cliCmd.Stderr = &stderr
	cliCmd.Stdout = &stdout

	cliCmd.Run()

	fmt.Println(stderr.String())
	fmt.Println(stdout.String())
}
```

Running on a Linux host, I get:

```
Args: []string{"/bin/sh", "-c", "az account show -o json  --subscription \"1234-456-789\""}

{
  "environmentName": "AzureCloud",
  "homeTenantId": "********-****-****-****-************",
  "id": "1234-456-789",
  "isDefault": true,
  "managedByTenants": [],
  "name": "team-ce",
  "state": "Enabled",
  "tenantDefaultDomain": "pulumi.onmicrosoft.com",
  "tenantDisplayName": "pulumi.com",
  "tenantId": "********-****-****-****-************",
  "user": {
    "name": "stoo@pulumi.com",
    "type": "user"
  }
}

```

Running on a Windows host (after switching the commented lines):

```
Args: []string{"cmd", "/C", "az account show -o json  --subscription \"1234-456-789\""}
ERROR: Subscription '"1234-456-789"' not found. Check the spelling and casing and try again.
```

**Comment by Zamiell** [comment]
Yeah, I get the same problem on Windows. This is a critical bug, as I had to revert the version of the package to 3.7.0.

**Comment by mjeffryes** [comment]
Yes, it looks like we might have regressed the function to fetch the default azure subscription for windows users. Probably  we can just adjust how we're escaping this for windows.

**Comment by EronWright** [comment]
## Root Cause Analysis

### Current Implementation

The `azure_cli.go` file (introduced in v3.8.0 via #4242) builds a command string with quotes around the subscription ID:

```go
commandLine := "az account show -o json "
if subscriptionID != "" {
    commandLine += ` --subscription "` + subscriptionID + `"`
}
```

This string is then executed through a shell:
- **Windows**: `exec.CommandContext(ctx, "cmd.exe", "/c", commandLine)`
- **Linux**: `exec.CommandContext(ctx, "/bin/sh", "-c", commandLine)`

### Observable Behavior

From @stooj's testing, the actual command arguments differ by platform:

**Windows:**
```
Args: []string{"cmd", "/C", "az account show -o json  --subscription \"1234-456-789\""}
ERROR: Subscription '"1234-456-789"' not found.
```

**Linux:**
```
Args: []string{"/bin/sh", "-c", "az account show -o json  --subscription \"1234-456-789\""}
(success - subscription found)
```

The error message on Windows shows the quotes are included as literal characters in the subscription ID: `'"1234-456-789"'`

### Code Derivation

The code comments reference the Azure SDK for Go:
```go
// this code is derived from "CLI token provider" code in the Azure SDK for Go:
// https://github.com/Azure/azure-sdk-for-go/blob/519e8ab1a0e433b755c31ebaa6b177dfc83cb838/sdk/azidentity/azure_cli_credential.go#L117-L172
```

The Azure SDK's current `developer_credential_util.go` uses the same shell-based execution pattern with command string concatenation.

### Impact

Affects Windows users in v3.8.0+ when a subscription ID is specified.

**Comment by EronWright** [comment]
## Additional Analysis: Azure SDK Impact

This issue occurs specifically when `subscriptionId` is configured on the provider.

### Why v3.7.0 Worked

In v3.7.0, the provider created `azidentity.AzureCLICredential` without passing a subscription ID:

```go
options := &azidentity.AzureCLICredentialOptions{
    AdditionallyAllowedTenants: authConf.auxTenants,
}
cli, err := azidentity.NewAzureCLICredential(options)
```

The provider simply used Azure CLI's default subscription even when configured otherwise, inadvertently avoiding the shell quoting issue entirely. 

### What Changed in v3.8.0

PR #4242 ("Decouple provider from go-autorest legacy system") made two changes:

1. **Added explicit subscription discovery** (`provider/pkg/provider/azure_cli.go:54-110`):
   - Calls `az account show --subscription "..."` 
   - This is where Windows users currently fail

2. **Started passing subscription ID to Azure SDK** (`provider/pkg/provider/auth_azidentity.go:217-220`):
   ```go
   if authConf.subscriptionId != "" {
       options.Subscription = authConf.subscriptionId
   }
   return azidentity.NewAzureCLICredential(options)
   ```

### Azure SDK Has Same Issue

The Azure SDK's [`azure_cli_credential.go`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/azure_cli_credential.go) uses identical shell quoting in `GetToken`:

```go
command += ` --subscription "` + c.opts.Subscription + `"`
```

This command is passed to the same `cmd.exe /c` execution pattern on Windows.

### Impact

Fixing only the provider's `azure_cli.go` would be incomplete:
1. Provider's `az account show` would succeed (if fixed)
2. Azure SDK's `az account get-access-token` would still fail on Windows with the same quoting issue

Both the provider code and the Azure SDK code need to be addressed.

**Comment by EronWright** [comment]
Filed an upstream bug report: https://github.com/Azure/azure-sdk-for-go/issues/25492

**Comment by stooj** [comment]
Re-opening this since the issue has been fixed upstream with version [v1.13.1 of azidentity](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fazidentity%2Fv1.13.1).

Is it possible to include the updated dependency in a new release please?

**Comment by thecodetinker** [comment]
FYI simply upgrading to 3.10 did not fix the issue for me. Fingers crossed for the upstream fix!

**Comment by blampe** [comment]
azidentity was bumped in https://github.com/pulumi/pulumi-azure-native/pull/4441, this will be included with the next release (or you can test the prerelease).

**Comment by pgavlin** [comment]
The bumped dep has been released with [v3.11.0](https://github.com/pulumi/pulumi-azure-native/releases/tag/v3.11.0). Closing this now.
